### ISSUE TITLE
This error occurs when my slider finishes executing

### ISSUE THREAD

**Issue by Leewinner1** [splashbyte/action_slider#11]
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ArgumentError was thrown building AnimatedBuilder(listenable:
AnimationController#e6f76(▶ 1.000)➩Cubic(0.42, 0.00, 0.58, 1.00), dirty, state:
_AnimatedState#b5ad8):
Invalid argument(s): 0.0

The relevant error-causing widget was:
  AnimatedBuilder
  AnimatedBuilder:file:///Users/lee/.pub-cache/hosted/pub.flutter-io.cn/action_slider-0.7.0/lib/src/action_sli
  der_widget.dart:899:16

When the exception was thrown, this was the stack:
#0      double.clamp (dart:core-patch/double.dart:234:7)
#1      _ActionSliderState.build.<anonymous closure>.<anonymous closure>.statePosToLocalPos
(package:action_slider/src/action_slider_widget.dart:906:46)
#2      _ActionSliderState.build.<anonymous closure>.<anonymous closure>
(package:action_slider/src/action_slider_widget.dart:907:30)
#3      ListenableBuilder.build (package:flutter/src/widgets/transitions.dart:1123:48)
#4      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:135:48)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#15     _invoke (dart:ui/hooks.dart:312:13)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#17     _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Invalid argument(s): 0.0
Another exception was thrown: Invalid argument(s): 0.0
Another exception was thrown: Invalid argument(s): 0.0
Another exception was thrown: Invalid argument(s): 0.0
```

**Comment by patrikSterbic** [comment]
I have same problem. Did you find some workaround for this?

**Comment by kundanlal5555** [comment]
Add Try Block on line no.
<img width="1113" alt="Screenshot 2024-01-24 at 2 04 07 AM" src="https://github.com/splashbyte/action_slider/assets/100687333/386f30da-1250-4d13-a268-662cffc4cc03">

**Comment by patrikSterbic** [comment]
Nice, thank you, that actually helped!

**Comment by maeddin** [comment]
I apologize for not taking care of this bug sooner. Unfortunately, I've had very little free time in the last few weeks to work on my open source projects.
This error occurs when the width is too small to display the indicator. What kind of behavior would you like to see in this situation? A useful error message would probably be useful.

**Comment by maeddin** [comment]
Can anyone who has experienced this error confirm that it no longer occurs in #12?

**Comment by alejandrogiubel** [comment]
I think the changes to this fix are not yet in the version published at https://pub.dev/, perhaps versioning problems

**Comment by maeddin** [comment]
@alejandrogiubel No, this fix has not yet been released. If you need this fix, you can use the current GitHub version in your Flutter project.

**Comment by alejandrogiubel** [comment]
@maeddin understood. That's what I did. thank you so much
